### ISSUE TITLE
python predict.py error

### ISSUE THREAD

**Issue by blair2020** [hbaudhuin/LamboiseNet#5]
(python3.6) root@0b492a6ce75b:/work/LamboiseNet-master# python predict.py 
Traceback (most recent call last):
  File "predict.py", line 9, in <module>
    from Models.lightUnetPlusPlus import lightUnetPlusPlus
  File "/work/LamboiseNet-master/Models/lightUnetPlusPlus.py", line 4, in <module>
    from Models.basicUnet import Downscaling_layer, DoubleConvolutionLayer, FinalLayer
  File "/work/LamboiseNet-master/Models/basicUnet.py", line 1, in <module>
    from torch import *
AttributeError: module 'torch' has no attribute 'unique_dim'

why 'from torch import *'?

**Comment by blair2020** [comment]
remove 'from torch import *' in File "/LamboiseNet-master/Models/basicUnet.py", line 1
and it's ok
